CREATE DATABASE CSDL
USE CSDL 
GO

CREATE TABLE DONVI(
 TENDV CHAR(20) PRIMARY KEY NOT NULL,
 CHINHANH CHAR(20)
)
CREATE TABLE NV(
 MANV CHAR (20) PRIMARY KEY NOT NULL,
 TENNV CHAR (20),
 TENDV CHAR(20) FOREIGN KEY(TENDV) REFERENCES DONVI(TENDV) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE DUAN(
 MADA CHAR (20) NOT NULL ,
 MANV CHAR (20) NOT NULL FOREIGN KEY(MANV) REFERENCES NV(MANV) ON UPDATE CASCADE ON DELETE CASCADE,
 THOIGIAN DATE,
 CONSTRAINT PK PRIMARY KEY(MADA, MANV) 
)

INSERT INTO DONVI VALUES
('TRUNG CAP', 'CN01'),
('THIEU TA', 'CN02'),
('THUONG TA', 'CN3')

INSERT INTO NV VALUES
('NV01', 'HUYEN', 'TRUNG CAP'),
('NV02', 'VI', 'THIEU TA'),
('NV03', 'NHUNG', 'THUONG TA'),
('NV04', 'CAN', 'TRUNG CAP')

INSERT INTO DUAN VALUES
('CT1', 'NV01', '2022-10-8'),
('CT8', 'NV02', '2023-10-8'),
('CT1', 'NV03', '2022-10-8'),
('CT20', 'NV02', '2022-11-8')

SELECT * FROM DONVI
SELECT * FROM NV
SELECT * FROM DUAN

--1
SELECT * FROM NV
SELECT TENNV, TENDV FROM NV

--2
INSERT INTO DONVI VALUES('PHO TA', 'HA NAM')
SELECT * FROM DONVI
INSERT INTO NV VALUES ('NV05', 'THUY', 'PHO TA')
SELECT * FROM NV

SELECT TENNV FROM NV
INNER JOIN DONVI ON DONVI.TENDV = NV.TENDV
WHERE CHINHANH LIKE 'HA NAM'

--3
SELECT * FROM NV
SELECT TENNV FROM NV
WHERE TENNV LIKE '[V]%'

--4
SELECT * FROM NV
SELECT * FROM DUAN

SELECT NV.MANV FROM NV
INNER JOIN DUAN ON DUAN.MANV = NV.MANV
WHERE MADA LIKE 'CT20' AND  NV.MANV NOT IN (SELECT MADA FROM DUAN )

--5
SELECT * FROM NV
SELECT * FROM DUAN
SELECT NV.MANV, COUNT(MADA) AS SODUAN FROM NV
INNER JOIN DUAN ON DUAN.MANV = NV.MANV
GROUP BY NV.MANV

--6
SELECT * FROM NV
SELECT * FROM DUAN
SELECT NV.TENNV FROM NV
INNER JOIN DUAN ON DUAN.MANV = NV.MANV
WHERE (THOIGIAN = (SELECT MIN(THOIGIAN) FROM DUAN)) AND MADA LIKE 'CT20'