
USE master
IF(EXISTS (SELECT * FROM SYSDATABASES WHERE NAME ='QLDAA'))
DROP DATABASE QLDAA
GO
CREATE DATABASE QLDA ON PRIMARY
(NAME ='QLDAA_DATA', FILENAME ='D:\QLDAA.MDF', SIZE = 20MB, MAXSIZE =100MB, FILEGROWTH = 10%)
LOG ON (NAME ='QLDAA_LOG', FILENAME ='D:\QLDAA.LDF', SIZE = 5MB, MAXSIZE =20MB, FILEGROWTH = 5%)
--TAO BANG VAT TU
USE QLDAA
GO

--TAO BANG NV
CREATE TABLE NV(
 MANV CHAR(20) NOT NULL PRIMARY KEY, HO CHAR(20) NOT NULL,TEN CHAR(20) NOT NULL,DIACHI CHAR(20) NOT NULL
)

CREATE TABLE DA(
 MADA INT NOT NULL PRIMARY KEY, TENDA CHAR(20) NOT NULL, NGANSACH MONEY NOT NULL
)

CREATE TABLE CC(
 MANV CHAR(20) NOT NULL FOREIGN KEY (MANV) REFERENCES NV(MANV) ON UPDATE CASCADE ON DELETE CASCADE,
 MADA INT NOT NULL FOREIGN KEY (MADA) REFERENCES DA(MADA) ON UPDATE CASCADE ON DELETE CASCADE,
 NGAYBD DATE NOT NULL,
 CONSTRAINT PK PRIMARY KEY (MANV, MADA)
)

INSERT INTO NV VALUES
(N'NV01', N'NGUYEN', N'TUYET MAI', N'HA NOI'),
(N'NV02', N'DO', N'TUYET MAI', N'HA NAM'),
(N'NV03', N'NGUYEN', N'TO NGA', N'HA NOI')

INSERT INTO DA VALUES
(N'1', N'MUA MAY TINH', 10000000),
(N'2', N'TRI TUE NHAN TAO', 6000000000),
(N'3', N'TAO', 1800000)

INSERT INTO CC VALUES
(N'NV01', N'1','10/1/2021'),
(N'NV02', N'1','10/10/2023'),
(N'NV01', N'3','10/11/2023')

--??A RA TOÀN B? THÔNG TIN B?NG
SELECT * FROM NV
SELECT * FROM DA
SELECT * FROM CC


--6. C?p nh?t l?i s? ngân sách c?a các d? án d??i 1 tri?u thành 5 tri?u. (0.5?)
UPDATE DA
SET NGANSACH = 5000000
WHERE NGANSACH <10000000
select * from DA


--A L?y ra mã và tên các d? án ngân sách t? 500 ??n 1000
SELECT * FROM DA
SELECT MADA, TENDA FROM DA WHERE NGANSACH BETWEEN 50000 AND 100000000

--B L?y ra tên và ??a ch? c?a nhân viên b?t ??u tham gia d? án ‘Nhà ? thông minh’ vào tháng 10 n?m 2021.
INSERT INTO DA VALUES (5, N'NHA O THONG MINH', 500000)
INSERT INTO CC VALUES (N'NV01', 5, '10/11/2021')
SELECT * FROM DA
SELECT * FROM CC
SELECT TEN, DIACHI FROM NV 
INNER JOIN CC ON NV.MANV = CC.MANV
INNER JOIN DA ON CC.MADA = DA.MADA
WHERE TENDA LIKE N'NHA O THONG MINH' AND MONTH(NGAYBD)=11 AND YEAR(NGAYBD)=2021

--C L?y ra mã, tên và ngân sách các d? án có tên b?t ??u b?ng ‘Trí tu?’ mà nhân viên có mã là K15 ?ã tham gia.
INSERT INTO NV VALUES ('K15', 'BUI','THI NGOC', 'BAI XUYEN')
INSERT INTO CC VALUES ('K15', '2', '9/11/2004')
SELECT * FROM NV
SELECT * FROM CC
SELECT DA.MADA, TENDA, NGANSACH FROM DA
INNER JOIN CC ON DA.MADA = CC.MADA
WHERE TENDA LIKE 'TRI TUE%' AND MANV = 'K15'

--D L?y ra tên nhân viên ch?a tham gia d? án nào
SELECT TEN FROM NV
WHERE MANV NOT IN (SELECT MANV FROM CC)

--E L?y ra mã d? án và s? nhân viên ?ã tham gia d? án ?ó tr??c ngày 25/12/2021
SELECT CC.MADA, COUNT (*) AS SONV FROM CC
INNER JOIN DA ON DA.MADA = CC.MADA
WHERE NGAYBD < '12/25/2021'
GROUP BY CC.MADA

--F L?y ra mã d? án có h?n 100 nhân viên tham gia ?ã k?t thúc vào tháng 12 n?m 2021
SELECT CC.MADA, COUNT (*) AS SONV FROM CC
INNER JOIN DA ON DA.MADA = CC.MADA
WHERE MONTH(NGAYBD) < 12 AND YEAR(NGAYBD) = 2021
GROUP BY CC.MADA
HAVING COUNT (*) > 100










--T?O CSDL
USE master
IF (EXISTS ( SELECT * FROM SYSDATABASES WHERE NAME = 'QLDA'))
DROP DATABASE QLDA
CREATE DATABASE QLDA 
USE QLDA

CREATE TABLE SINHVIEN(
 MASV CHAR(20) NOT NULL PRIMARY KEY,
 TENSV CHAR(20) NOT NULL,
 NGAYSINH DATE NOT NULL,
 QUEQUAN CHAR(20) NOT NULL,
 GIOITINH BIT NOT NULL
)

CREATE TABLE MOONHOC(
 MAMH CHAR(20) NOT NULL PRIMARY KEY,
 TENMH CHAR(20) NOT NULL,
 SOTC INT
)

CREATE TABLE DIEEM(
 MASV CHAR(20) NOT NULL FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV) ON UPDATE CASCADE ON DELETE CASCADE,
 MAMH CHAR(20) NOT NULL FOREIGN KEY (MAMH) REFERENCES MOONHOC(MAMH) ON UPDATE CASCADE ON DELETE CASCADE,
 DIEMTHI INT,
 CONSTRAINT PK_MASV_MAMH PRIMARY KEY(MASV, MAMH)
)

INSERT INTO SV VALUES
('SV01', 'NGUYEN  THE TUAN', '2002-03-05', 'HA NOI', 'NAM'),
('SV02', 'LE THI TRANG', '2003-01-06', 'HA NAM', 'NU'),
('SV03', 'TRAN VAN MINH', '2002-03-14', 'NAM DINH', 'NAM'),
('SV04', 'PHAM MINH HUNG', '2002-04-07', 'HA NOI', 'NAM'),
('SV05', 'NGUYEN THI LAN', '2003-03-22', 'HA NAM', 'NU')

INSERT INTO MONHOC VALUES
('M01', N'TOAN GIAI TICH', '4'),
('M02', N'HE QUAN TRI CSDL', '3'),
('M03', N'LAP TRINH JAVA', '3')

INSERT INTO DIEM VALUES
('SV01', 'M01', '9'),
('SV01', 'M02', '7'),
('SV02', 'M01', '6'),
('SV03', 'M02', '5'),
('SV04', 'M01', '4')

--??A RA TOÀN B? THÔNG TIN B?NG
SELECT * FROM SV
SELECT * FROM MONHOC
SELECT * FROM DIEM

--??A RA 1 S? C?T TRONG B?NG
SELECT MASV, TENSV, GIOTINH FROM SV

--TOP N/ TOP N PERCENT
SELECT TOP 3 * FROM SV
SELECT TOP 3 MASV, TENSV FROM SV
SELECT TOP 30 PERCENT * FROM SV

--S?P X?P GI?I TÍNH SINH VIÊN TANG D?N ASC
SELECT * FROM SV ORDER BY GIOITINH ASC
SELECT * FROM SV ORDER BY GIOITINH DESC
SELECT * FROM SV ORDER BY GIOITINH ASC, QUEQUAN DESC

--??A RA TOP 2 ?I?M THI CAO NH?T
SELECT TOP 2 MASV, DIEMTHI FROM DIEM ORDER BY DIEMTHI ASC

--L?C D? LI?U WHERE
--??a ra sv quê quán hà n?i
SELECT * FROM SV WHERE QUEQUAN = N'HA NOI'
--??a ra sinh viên là n? và quê hà nam
SELECT * FROM SV WHERE GIOITINH=N'NU' and QUEQUAN=N'HA NAM'

--HÀM IN/NOT IN
--??a ra sv quê hà n?i, b?c ninh, h?i d??ng
SELECT * FROM SV WHERE QUEQUAN IN(N'HA NOI', N'BAC NINH', N'HAI DUONG')

--BETWEEN..AND
--??a ra masv, mamh co ?i?m thi t? 7-9
SELECT MASV, MAMH, DIEMTHI FROM DIEM WHERE DIEMTHI BETWEEN 7 AND 9

--LIKE N'%CHU?I%'
-- % : kí hi?u cho phía sau ho?c phía tr??c còn thông tin
--??a ra các sv có h? Nguy?n
SELECT * FROM SV WHERE TENSV LIKE N'NGUYEN%'
SELECT * FROM SV WHERE TENSV LIKE N'%THI%'
SELECT * FROM SV WHERE TENSV LIKE N'%HUYEN'

--NGÀY THÁNG
SELECT GETDATE()
SELECT MONTH(GETDATE())
SELECT YEAR(GETDATE())
--tu?i
SELECT MASV, TENSV, YEAR(GETDATE())-YEAR(NGAYSINH) AS TUOI FROM SV
